version: '2'

services:

    snappass:
        build: .
        image: snappass:latest
        ports:
            - "5000:5000"
        stop_signal: SIGINT
        environment:
            - REDIS_HOST=redis
            - HOST_OVERRIDE=secrets.tservic.es
        depends_on:
          - redis

    redis:
        image: "redis:latest"
